/**
 * syncAgentSamples.js —— 把「示例源」同步成「公开产物」（2026-09-24）
 *
 * 背景（用户关切）：样例代码只该有一处手改的地方。若在 examples/ 和 public/ 各放一份，
 * 改一处忘一处就会**静默漂移** —— 而漂移的后果特别隐蔽：来访 AI 下载到的是旧版说明书，
 * 我们这边看不出来。
 *
 * 因此约定：**唯一手改源 = examples/agent-client/**，**产物 = public/agent-samples/**。
 * 产物由本脚本生成（文件头写死 "GENERATED / 勿手改"），任何人都不该直接改产物。
 *
 * 为什么落 public/：express.static 只托管 public/（见 src/server.js:102），examples/ 线上
 * 取不到 —— 而 llms.txt 要指一份"陌生 AI 一个 curl 就能拿走"的参考实现，必须走 HTTP。
 *
 * 用法：
 *   node scripts/syncAgentSamples.js           写入/更新产物（漂移时自动修复）
 *   node scripts/syncAgentSamples.js --check   只校验，漂移或缺失则退出码 1（可挂 CI / 上传前自检）
 *
 * 注意：产物头里**不写生成时间** —— 否则每次运行都产生 diff，--check 永远失败。
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC_DIR = path.join(ROOT, 'examples', 'agent-client');
const OUT_DIR = path.join(ROOT, 'public', 'agent-samples');

/** 要同步的文件（顺序无关；成对关系写在 llms.txt 里向外部声明） */
const FILES = ['ai-chat-loop.mjs', 'loop-addressing.mjs'];

/** 产物头：静态文本，不含时间戳（见文件头说明）。只占 2 行 —— 产物也要守住 ≤500 行红线 */
const HEADER = [
  '// GENERATED by scripts/syncAgentSamples.js —— 勿手改，改了下次同步即被覆盖（源：examples/agent-client/）',
  '// DO NOT EDIT. Regenerate: node scripts/syncAgentSamples.js',
  ''
].join('\n');

function build(name) {
  const src = path.join(SRC_DIR, name);
  if (!fs.existsSync(src)) {
    throw new Error(`源文件不存在：${path.relative(ROOT, src)}`);
  }
  return { out: path.join(OUT_DIR, name), content: HEADER + fs.readFileSync(src, 'utf8') };
}

function main() {
  const checkOnly = process.argv.includes('--check');
  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

  const drifted = [];
  const ok = [];
  for (const name of FILES) {
    const { out, content } = build(name);
    const current = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : null;
    if (current === content) {
      ok.push(name);
      continue;
    }
    const why = current === null ? '缺失' : '内容不一致（源已更新或产物被手改）';
    drifted.push(`${name}（${why}）`);
    if (!checkOnly) {
      fs.writeFileSync(out, content, 'utf8');
      console.log(`[sync] 已写入 public/agent-samples/${name}`);
    }
  }

  if (ok.length) console.log(`[sync] 已是最新：${ok.join(', ')}`);
  if (drifted.length) {
    if (checkOnly) {
      console.error(`[sync] 漂移：${drifted.join('；')}\n[sync] 请运行 node scripts/syncAgentSamples.js 后重新上传产物。`);
      process.exit(1);
    }
    console.log(`[sync] 修复漂移：${drifted.join('；')}`);
  }
  console.log(`[sync] 完成（源=${path.relative(ROOT, SRC_DIR)}，产物=${path.relative(ROOT, OUT_DIR)}）`);
}

main();
